### ISSUE TITLE
Question: Run on pull request

### ISSUE THREAD

**Issue by johlju** [jonabc/licensed-ci#47]
Is it possible to run tis GitHub Action on pull requests to fail the build if the PR adds a new package with a license that is not acceptable?

On pull request I'm getting `Error: refs/pull/14/merge does not reference a branch`. Looks like it was meant to have been fixed according to https://github.com/jonabc/licensed-ci/issues/44#issuecomment-699157465, but might not be?

I used the trigger configuration like so:

```yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```
