### ISSUE TITLE
How do I actually run this tool?

### ISSUE THREAD

**Issue by S3j5b0** [jonabc/licensed-ci#58]
Hi, im trying to set up a gtihub action, and using your tool for scanning.

I have this yml file:

```

name: "Update and check dependency data"


on:
  push:
    branches: [main]


jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jonabc/licensed-ci@v1
      - uses: jonabc/setup-licensed@v1
        with:
         version: 2.x
      - run: licensed list

```

Where I would like to run "licensed status" on my project.
But of course this does not work, and the command "licensed" cannot be found.

How do I get to use the commands from your library? 
I dont really understand the examples on your marketplace page, none of them seem to be actually using the comands, they just run a few scripts and so on

**Comment by jonabc** [comment]
:wave: @S3j5b0 the issue here is that you've got `@jonabc/licensed-ci` running before `@jonabc/setup-licensed`.  setup-licensed installs a distributable licensed+ruby executable to make it available for later actions.  licensed-ci expects that licensed has been installed and can be found on `$PATH`, so these two actions are made to work together well.

> I dont really understand the examples on your marketplace page, none of them seem to be actually using the comands, they just run a few scripts and so on

I'm not sure what you mean, the examples on the marketplace page all use `licensed-ci`.  The examples show how to use licensed based on two different methods for installing licensed itself.  Is there something else you'd like to see that's missing?

**Comment by S3j5b0** [comment]
Thanks a lot for the answer!

I now have this setup:

name: "Update and check dependency data"

name: "Update and check dependency data"

```
on:
  push:
    branches: [main]

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jonabc/setup-licensed@v1
        with:
         version: 2.x
         
      - uses: jonabc/licensed-ci@v1
      - run: licensed list
```



Which fails with:
`ENOENT: no such file or directory, access '.licensed.yml'`

Should i have a licensed.yml file somewhere?
 
If i completely remove 'licensed-ci@v1' then it gives me:

` `find_config': Licensed configuration not found in /home/runner/work/malware/malware (Licensed::Configuration::LoadError)`

**Comment by jonabc** [comment]
yes, licensed requires a [configuration file](https://github.com/github/licensed#configuration) to work.  the default configuration file location is `<repo root>/.licensed.yml` and the [config file documentation](https://github.com/github/licensed/blob/master/docs/configuration.md) gives some information about the different configuration options.

Most of the configuration is optional, the only thing you should need to set to get up and running with `licensed status` to work is the `allowed` licensed list.  The [example configuration](https://github.com/github/licensed/blob/master/docs/configuration.md#applications) shows this configuration with a descriptive comment.

**Comment by S3j5b0** [comment]
thanks a lot for the help, I think im getting there, running licensed status now gives me:


```
 * My application
    - No such directory /home/runner/work/malware/malware/relative/path/from/configuration/file/directory/relative/path/to/source
```

**Comment by S3j5b0** [comment]
I realize I should probably set these to something, but what should they be pointing to?

```

root: 'relative/path/from/configuration/file/directory'

cache_path: 'relative/path/to/cache'


source_path: 'relative/path/to/source'
```
root, should that just be the root? so "."

for "cache_path" I really dont know? where I metadata stored? is it metadata somewhere in my repo or in the github action enviorment?

"source_path" I dont understand either? what should this be a path to?

**Comment by S3j5b0** [comment]
Great, now it runs as it should

The only problem now, is that licensed status has this output:
`
 dependencies checked, 0 errors found.`

And also when I delete my license file, the same output persists, how do I get it to check the license and dependencies of licenses?

**Comment by jonabc** [comment]
`root`: if you are in a git repository you don't need to set this, it will default to the repository root
`cache_path`: this is the path that the metadata files that licensed-ci creates are stored.  it defaults to a `.licenses` folder at the root of the repo, again you don't need to set it unless you want to override that value
`source_path`: this is the path to the code you're finding licenses for and defaults to the directory that licensed is run from if not set.  when using the [bundler source](https://github.com/github/licensed/blob/master/docs/sources/bundler.md) this needs to be the directory path that contains `Gemfile` and `Gemfile.lock`.

The "happy path" is to have `.licensed.yml` at the root of the repository and to run licensed commands from the root of the repository, and not set `root` and `cache_path`.  If `Gemfile` and `Gemfile.lock` are at the root of the repo, then you don't need to set `source_path` either.  If they are not at the root of the repository, you'll need to set `source_path` to a path relative to the repository root of the folder containing `Gemfile` and `Gemfile.lock`

To preempt another possible point of confusion, licensed looks at dependencies that are installed on the local disk.  You'll need to ensure that you've installed dependencies locally before running any `licensed` commands - i.e. `bundle install` or whatever local scripting you have to accomplish the same.

**Comment by S3j5b0** [comment]
My project is golang, would this mean that I would have to run something like:


   uses: actions/setup-go@v2
   run:  go get "github.com/yuin/goldmark v1.2.1/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74="

before calling licensed? 
running this toy example doesnt seem to have any effect

**Comment by jonabc** [comment]
> My project is golang, would this mean that I would have to run something like:
> uses: actions/setup-go@v2
> run: go get "github.com/swaggo/http-swagger"
> before calling licensed?

Yep 👍 .  In that case the issue may be that your source path is not set up properly.  For go projects you'll need to set source path to the entry point of your app.  A good way to test this is running `go list -e -json -deps .` in a directory and seeing what is output.  That's the command licensed uses internally to determine what dependencies are available

**Comment by S3j5b0** [comment]
the file that I use to start the project is just in the root dir that would be the entry point right?,
. running 'go list -e -json -deps .'  gives me a really long list of dependencies in json-format

**Comment by jonabc** [comment]
👍 yeah the root dir would be the source_path in that case.  I don't see anything immediately obvious in your action YML, maybe change the following to get all dependencies rather than just those two?

From:
```yaml
      - run: go get "github.com/gorilla/mux"
      - run: go get "github.com/sirupsen/logrus"
```

To:
```yaml
      - run: go get
```

Can you also paste the licensed configuration file contents here?

**Comment by S3j5b0** [comment]
good idea! 
here is licensed:

```

name: 'My application'


sources:
  bower: true
  bundler: false

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc


ignored:
  bundler:
    - some-internal-gem

  bower:
    - some-internal-package

reviewed:
  bundler:
    - bcrypt-ruby

  bower:
  - classlist # public domain
  - octicons
```
